### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by ALitKi** [XYZliang/JiangxiYouthStudyMaker#10]
![image](https://user-images.githubusercontent.com/39232323/169689037-47731b0f-90be-438f-abf8-9bf4c87f38f5.png)
@kongminhao 大佬这个怎么解决呀

**Comment by ALitKi** [comment]
![image](https://user-images.githubusercontent.com/39232323/169689202-e1248e7b-8b40-40ba-9f9f-dfd0878cb5e8.png)

**Comment by ALitKi** [comment]
![image](https://user-images.githubusercontent.com/39232323/169689224-72de6680-b1b5-4f82-ba5f-f20397c92ad0.png)

**Comment by kongminhao** [comment]
服务器挂了似乎，你应该正常打卡也会失败，等下周再说吧。

**Comment by XYZliang** [comment]
全部更换最新接口
