### ISSUE TITLE
接口是不是挂了，今天告知我们后台地址也换了一个

### ISSUE THREAD

**Issue by zf4299498** [XYZliang/JiangxiYouthStudyMaker#11]
![image](https://user-images.githubusercontent.com/56245317/169749278-2f56a0b2-00ed-4773-904c-c9f494ab3c6e.png)

**Comment by zf4299498** [comment]
新接口http://www.jxqingtuan.cn/pub/vol/volClass/join?accessToken=

**Comment by XYZliang** [comment]
全部更换最新接口
