### ISSUE TITLE
多人批量好像还是执行不了

### ISSUE THREAD

**Issue by jiangxi-am** [XYZliang/JiangxiYouthStudyMaker#13]
![1a040efdcdfb4825](https://user-images.githubusercontent.com/57026429/170639489-e7ddbd8f-2c45-4387-adb2-f1888c5f9056.png)
![47f122dd2bee0b79](https://user-images.githubusercontent.com/57026429/170639505-f6a7077f-f054-49c0-80a9-09a581209b37.png)
你好，请问下我这个应该怎么解决，单人能够正常使用

**Comment by ALitKi** [comment]
同问

**Comment by jiangxi-am** [comment]
上个版本就报这个错误
我还以为就我没成功...

**Comment by XYZliang** [comment]
第一个错误是因为xlrd的版本标高了，正确的是1.2.0版本，自动生成要求版本包时生成错了没注意。
改成1.2.0后我使用正常，没有第二个截图的错误
<img width="399" alt="image" src="https://user-images.githubusercontent.com/59312540/170848647-3f878368-770e-42b5-8d5c-85b40d6269d4.png">

**Comment by XYZliang** [comment]
第二个是编码问题，我试了几个环境没法复现，而且你出错的代码在单人版里也有。。居然能单人版正常。
新版只能尝试修复了，不知道是否有效，应该是你环境的编码有问题。
[UnicodeEncodeError: 'latin-1' codec can't encoding characters #1822](https://github.com/psf/requests/issues/1822#issue-24602748)
[https://blog.csdn.net/weixin_48960305/article/details/123826824](python发送post请求报编码错误)

**Comment by ALitKi** [comment]
> 第二个是编码问题，我试了几个环境没法复现，而且你出错的代码在单人版里也有。。居然能单人版正常。 新版只能尝试修复了，不知道是否有效，应该是你环境的编码有问题。 [UnicodeEncodeError： 'latin-1' 编解码器无法编码字符 #1822](https://github.com/psf/requests/issues/1822#issue-24602748) [https://blog.csdn.net/weixin_48960305/article/details/123826824](python%E5%8F%91%E9%80%81post%E8%AF%B7%E6%B1%82%E6%8A%A5%E7%BC%96%E7%A0%81%E9%94%99%E8%AF%AF)
用了最新的还是出现了这个问题，
![image](https://user-images.githubusercontent.com/39232323/170861721-43ddc901-629f-4def-98cd-732856377169.png)

**Comment by YANGNIGHT** [comment]
> 第二个是编码问题，我试了几个环境没法复现，而且你出错的代码在单人版里也有。。居然能单人版正常。 新版只能尝试修复了，不知道是否有效，应该是你环境的编码有问题。 [UnicodeEncodeError: 'latin-1' codec can't encoding characters #1822](https://github.com/psf/requests/issues/1822#issue-24602748) [https://blog.csdn.net/weixin_48960305/article/details/123826824](python%E5%8F%91%E9%80%81post%E8%AF%B7%E6%B1%82%E6%8A%A5%E7%BC%96%E7%A0%81%E9%94%99%E8%AF%AF)

能说明一下openid获取的地方吗，从点进公众号之前就开始抓一直到点击开始学习也没有找到openid

**Comment by XYZliang** [comment]
> > 第二个是编码问题，我试了几个环境没法复现，而且你出错的代码在单人版里也有。。居然能单人版正常。 新版只能尝试修复了，不知道是否有效，应该是你环境的编码有问题。 [UnicodeEncodeError: 'latin-1' codec can't encoding characters #1822](https://github.com/psf/requests/issues/1822#issue-24602748) [https://blog.csdn.net/weixin_48960305/article/details/123826824](python%E5%8F%91%E9%80%81post%E8%AF%B7%E6%B1%82%E6%8A%A5%E7%BC%96%E7%A0%81%E9%94%99%E8%AF%AF)
> 
> 能说明一下openid获取的地方吗，从点进公众号之前就开始抓一直到点击开始学习也没有找到openid

最明显的就是点去学习的时候，请求了一个join接口，accesstoken就是openid

**Comment by XYZliang** [comment]
> > 第二个是编码问题，我试了几个环境没法复现，而且你出错的代码在单人版里也有。。居然能单人版正常。 新版只能尝试修复了，不知道是否有效，应该是你环境的编码有问题。 [UnicodeEncodeError： 'latin-1' 编解码器无法编码字符 #1822](https://github.com/psf/requests/issues/1822#issue-24602748) [https://blog.csdn.net/weixin_48960305/article/details/123826824](python%E5%8F%91%E9%80%81post%E8%AF%B7%E6%B1%82%E6%8A%A5%E7%BC%96%E7%A0%81%E9%94%99%E8%AF%AF)
> > 用了最新的还是出现了这个问题，
> > ![image](https://user-images.githubusercontent.com/39232323/170861721-43ddc901-629f-4def-98cd-732856377169.png)

那只能建议你换环境了

**Comment by YANGNIGHT** [comment]
用pip安装anti_useragent老是会报错，虽然用其他方法安装上了，这个模块好像是生成headers的吧，能直接用固定的headers来去掉这个模块吗
![图片](https://user-images.githubusercontent.com/79457406/171147618-11849978-a14a-4015-ba38-399f5eaeec04.png)

**Comment by XYZliang** [comment]
> 用pip安装anti_useragent老是会报错，虽然用其他方法安装上了，这个模块好像是生成headers的吧，能直接用固定的headers来去掉这个模块吗 ![图片](https://user-images.githubusercontent.com/79457406/171147618-11849978-a14a-4015-ba38-399f5eaeec04.png)

如果你单人使用，可以。多人提交ua相同可能会造成一定的危险
搜不到应该是清华源还没更新过来。可以换回官方源然后科学上网

**Comment by XYZliang** [comment]
搜不到应该是清华源还没更新过来。可以换回官方源然后科学上网

**Comment by jiangxi-am** [comment]
![新版](https://user-images.githubusercontent.com/57026429/171409957-e5d08da7-758b-4d72-bda7-869223cab30f.png)
今天试了一下，好像解决了，现在正常运行，就是makers.py里面的excel表没有改过来哦“192.xlsx”

**Comment by XYZliang** [comment]
> ![新版](https://user-images.githubusercontent.com/57026429/171409957-e5d08da7-758b-4d72-bda7-869223cab30f.png) 今天试了一下，好像解决了，现在正常运行，就是makers.py里面的excel表没有改过来哦“192.xlsx”

哈哈我忘记改了
