### ISSUE TITLE
小提醒:openid的获取

### ISSUE THREAD

**Issue by YANGNIGHT** [XYZliang/JiangxiYouthStudyMaker#14]
1.电脑端抓包获取openid的get url为GET /pub/vol/member/login?code=031uXrr00NFrVN1hto200Thgke4uXl0q&state= HTTP/1.1在响应体header里会返回一个location的url，这个url最后就有openid=xxxxxxxxxxxxxxxxxxxxx
2.在手机端抓包没有openid,只有accesstoken，这个就是openid

**Comment by XYZliang** [comment]
他们一直在改动，刚抓包一遍确实变了写东西，一会改进脚本

**Comment by XYZliang** [comment]
这个code好像就是openid

**Comment by XYZliang** [comment]
和accesstoken一样

**Comment by YANGNIGHT** [comment]
> 这个code好像就是openid

我抓包的时候accesstoken = openid 但是跟这个code不一样，有这个code在这个url链接里才能返回accesstoken

**Comment by XYZliang** [comment]
login接口确实携带了一串code，但返回的accesstoken还就是openid，后续也没有用到code，所以一切照常，也不需要去模拟login这个接口的请求。就算没有openid，提交还是依旧生效

**Comment by XYZliang** [comment]
[移动应用微信登录开发指南](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Development_Guide.html)
> 第一步：请求 CODE
> 
> 移动应用微信授权登录
> 
> 开发者需要配合使用微信开放平台提供的 SDK 进行授权登录请求接入。正确接入 SDK 后并拥有相关授权域（scope）权限后，开发者移动应用会在终端本地拉起微信应用进行授权登录，微信用户确认后微信将拉起开发者移动应用，并带上授权临时票据（code）。



根据微信开发者文档，code是一次性生成的，交给程序后端去向微信请求我们的openid，所以code的值无需关心，既然会抓包能拿到openid就无后顾之忧。

**Comment by XYZliang** [comment]
根据微信开发者文档，code是一次性生成的，交给程序后端去向微信请求我们的openid，所以code的值无需关心，既然会抓包能拿到openid就无后顾之忧。

**Comment by YANGNIGHT** [comment]
> 根据微信开发者文档，code是一次性生成的，交给程序后端去向微信请求我们的openid，所以code的值无需关心，既然会抓包能拿到openid就无后顾之忧。

OK
