### ISSUE TITLE
现在青年大学习又更新了，我尝试抓包，但是好像没成功

### ISSUE THREAD

**Issue by YYYHeart** [XYZliang/JiangxiYouthStudyMaker#15]
现在的青年大学习网站域名改成了这个https://h5.cyol.com
抓包就没有发送包，就看到了返回成功的包
![sign](https://user-images.githubusercontent.com/62085029/172767579-e70ee1d0-af4a-4d90-a4ae-04959477e6c9.png)
![ok](https://user-images.githubusercontent.com/62085029/172767587-abf00177-0fcf-4278-9f47-277e5db325e5.png)

**Comment by YYYHeart** [comment]
第一张图片是点进网上团课，第二张是点击开始学习

**Comment by XYZliang** [comment]
![IMG_3484](https://user-images.githubusercontent.com/59312540/173126512-adaaca18-4bf2-4a30-a10f-0c610646ee47.jpeg)

**Comment by XYZliang** [comment]
系统更新完毕，正常使用
