### ISSUE TITLE
手机抓包是哪个url，大佬们

### ISSUE THREAD

**Issue by huajianxiaowanzi** [XYZliang/JiangxiYouthStudyMaker#17]

**Comment by huajianxiaowanzi** [comment]
不是抓江西共青团公众号吗？

**Comment by XYZliang** [comment]
你那时候抓，系统还在维护，抓不到的。
现在系统开启了，你可以去抓了，找到如下的链接
`http://www.jxqingtuan.cn/pub/vol/volClass/**join**?accessToken=XXXXXXXX`
对应的数据：
`{"course": course, "subOrg": subOrg, "nid": nid, "cardNo": cardNo}`
