### ISSUE TITLE
多人学习版本、不用excel表格、直接用数据;

### ISSUE THREAD

**Issue by ArinWu** [XYZliang/JiangxiYouthStudyMaker#19]
`
text = '吴宁乐吴朝辉吴樟彪吴红陵吴锦萍吴卓铠吴英吴旻晗吴炯乐吴炯乐吴卓凯吴薇薇吴铭晗吴知倍吴嘉瑜吴乐微吴樟彪吴微薇吴旻涵吴薇微吴军吴旻涵吴建澄吴罕砚吴悠吴旻邯吴正军吴攸吴晨吴旻函吴雪慈吴阳吴震宇吴旻函吴艾穆吴春颖吴越吴沛昆吴镕而吴柏熹吴春芝吴薇薇吴尚纯吴多多吴洁吴香凝吴淑君吴晓东吴隽吴晨光吴嫒颖吴培宏吴庆永吴娆颖吴旻函吴梦春吴沛吴若慈吴振宝吴诗泽吴方春吴曼荧吴极吴婉荧吴雪荧吴沛俊吴桐宇吴梦琦吴宇桐吴佳骏吴洁吴虹吴晓吴歌吴戈吴桐吴春秀吴蕊妍吴梦坤吴蕙妍吴晨焱吴秋语吴思语吴奕菲吴天戈吴震宇吴凯鸣吴静华吴霞吴雪吴燕君吴君燕吴坤吴懿静吴子琼吴懿熹吴运芬吴梦酉吴云月吴芸芸吴云吴梦佑吴子昂吴芸芸吴迪吴雪子吴一诺吴为峰吴昊吴幸颐吴梦昊吴幸熹吴梦凯吴树棠吴凯吴磊吴彤吴香凝吴昕倩吴博吴光红吴春燕吴君妍吴洋吴春苑吴阳吴瑞吴梦洋吴丽吴佳荣吴凡吴梦辉吴熙吴青华吴梦昊吴梦杰吴远哲吴丽华吴梦东吴梦哲吴丽柯吴卫萍吴旭吴卫萍吴海卓吴卓锴吴春芳吴梦良吴春方吴淑生吴侅卓吴林宸吴函卓吴伟吴村方吴侅卓吴椿方吴霖书吴鼎秀吴玉涵吴明潼吴靖吴荣嘉吴嘉瑞吴宛芝吴叔杰吴蜜林吴嘉丽吴雨霏吴亚吴吴欣邛吴嘉琳吴晓峰吴艳萍吴佳佳吴域涵吴佳吴嘉格吴春燕吴爱媛吴爱瑗吴春嫒吴圩涵吴金昊吴玉婷吴泽坤吴炎骨吴学深吴雪玲吴清城吴杨吴泽坤吴为吴杰吴春谚吴炳锟吴歌吴嘉格吴国立吴青芳吴姝璇吴君怡吴青蓉吴松万吴春芳吴禹桥吴南吴青蓉吴春方吴春蓉吴青蓉吴壑清吴娜佳吴春芩吴青芳吴春蓉吴青蓉吴岩峰吴继银吴林桓吴泓葆吴秋蓉吴玉佳吴济吟吴俊吴佳清吴蕾吴青谚吴佳涵吴政霏吴玉地吴丹阳吴晓蕾吴舒同吴玉垚吴蓉吴清垚吴嘉格吴炳晔吴晗悦吴舒童吴圻涵吴青芩吴晗韵吴沂洲吴笑琪吴青蓉吴承茗吴函悦吴迦格吴凡吴泓葆吴春蓉吴嘉欣吴玉坚吴婧田吴嘉钥吴悦柯吴奔吴楠吴嘉格吴婧甜吴嘉鑫吴南吴玉坤吴旻峰吴语城吴玉清吴楠南吴语丞吴海珍吴怡欣吴青蓉吴钥馨吴承恩吴韵琪吴冬吴承圣吴紫馨吴波特吴承国吴立东吴春芳吴邦国吴冉琪吴为治吴波特吴官尚吴慧贤吴为至吴思霖吴若涵吴爽吴东星吴悦冉吴伟吴梅格吴笑康吴念宗吴建亮吴贝儿吴悦冉吴承靖吴盼吴昊天吴迪凡吴明刚吴长青吴东翁吴卓豪吴大伟吴怡欢吴承境吴承静吴一凡吴泽华吴蓓蓓吴希泠吴韩吴承谕吴思瑾吴涵吴韵紫吴承裕吴巧茹吴朔吴承予吴波吴仪吴硕吴亚锋吴达吴晨希吴海笑吴承昱吴禾真吴承煜吴希童吴清疆吴禧童吴继强吴惊喜吴墉洋吴东立吴承语吴诗雅吴淑勉吴曼奴吴韩吴飞吴承谕吴冬立吴非吴亦舒吴梦泽吴承靖吴振荣吴天弋吴圩涵吴墉源吴秋芳吴培源吴洪永吴晨玮吴培渊吴培源吴雪丽吴鹏吴雪利吴少锋吴雪莉吴雪犁吴亚胜吴明吴文吉吴泽华吴树棠吴文洁吴正宇吴培清吴文杰吴振荣吴金荣吴雪丽吴奕恺吴忠迅吴四红吴奕锴吴生祥吴洪云吴奕恺吴培汉吴世宏吴奕吴奉举吴世弘奕佳吴桐吴世洪吴柏举吴蔓菁吴世鸿吴世哄吴世虹吴世烘吴厚忠吴四红吴开放吴朝友吴厚宏吴帅吴坤涵吴良定吴正月吴金鸿吴良定吴楠吴坤涵吴冰吴江吴天晴吴培江吴雨晴吴捷吴海燕吴倩舒吴建珍吴厚弘吴厚洪吴生祥吴铸鉴吴厚仁吴镭吴厚军吴绅'
if __name__ == '__main__':
    Course = getCourse()
    data = xlrd.open_workbook(r'Data.xlsx')
    dataSheets = data.sheets()[0]
    row = dataSheets.nrows
    
    #print("开始批量提交!")
    """
    for i in tqdm(range(row)):
        rowData = dataSheets.row_values(i)
        #rowData ['吴啊', '', 'N0005000310011002', '']
        #print(rowData)
        studyData = []
        #studyData = rowData 1 ，2，3, 4
        
        for a, b in enumerate(rowData):
            studyData.append(b)
            #print(a, b)
            #print(studyData)

        if need_subOrg: #false 不执行
            getStudy(Course, studyData[2], studyData[1], studyData[0], studyData[3])
        else: # 默认执行 传参数
            getStudy(Course, studyData[2], "", studyData[0], studyData[3])
        #暂停时间
        time.sleep(random.uniform(0, stop))
     newstr = text.split('吴')
     #print(newstr)
     #'盼', '昊天', '迪凡',
     """
		

    newstr = text.split('吴') 
    for num in range(1, 100): #次数
        ran = round(random.random() * len(newstr))
        name = '吴' + newstr[ran]
        #body={"course":"20","subOrg":'null',"nid":"N0005000310011002","cardNo":name}
        ##print(num)
        #r=requests.post(url=url,json=body)
        #print(r.text)
        studyData = [ name , '', 'N0005000310011002', '']
        getStudy(Course, studyData[2], "", studyData[0], studyData[3])
        time.sleep(random.uniform(0, stop))	
    print("批量提交完毕!")
`

**Comment by XYZliang** [comment]
我不明白这有什么意义？哪个班姓同一个？
多人班的意义就是为了多人甚至多班级多组织进行提交
早晚有一天，人家系统会封禁没提交openid都能学习的方法，你还不是得用表格存储

**Comment by ygxiuming** [comment]
额，我不明白，谁不晓得用数据，为什么用表格不就是方便嘛，直接复制粘贴，你把数据放进去又要排版又要写逻辑关系。这不脱裤子放屁吗？

**Comment by XYZliang** [comment]
> 额，我不明白，谁不晓得用数据，为什么用表格不就是方便嘛，直接复制粘贴，你把数据放进去又要排版又要写逻辑关系。这不脱裤子放屁吗？

全放一起怎么分割人名？怎么分割可能后面需要用的openid？是整个班都姓吴还是整个班人名都是两个字？

**Comment by XYZliang** [comment]
即使假设你写个列表存，又要打引号又要加逗号分隔符号，你是嫌代码太短了不好看么？第一次见人把一大堆数据塞在代码里的

**Comment by ygxiuming** [comment]
我不晓得你在说什么。你要取数据，这不是很简单的东西吗？你可以第1列放openid，第2列方姓名。第3列放班级什么鬼东西？一个个拿数据不就行了，怎么会分割不了？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月19日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XYZliang/JiangxiYouthStudyMaker] 多人学习版本、不用excel表格、直接用数据; (Issue #19)




  
额，我不明白，谁不晓得用数据，为什么用表格不就是方便嘛，直接复制粘贴，你把数据放进去又要排版又要写逻辑关系。这不脱裤子放屁吗？
  
全放一起怎么分割人名？怎么分割可能后面需要用的openid？是整个班都姓吴还是整个班人名都是两个字？

**Comment by XYZliang** [comment]
你看你自己改的什么鬼
`newstr = text.split('吴') `，我也是看笑了
数据全放代码里方便管理？

**Comment by XYZliang** [comment]
几十上百人的数据，万一要删哪个人，找不死你？

**Comment by XYZliang** [comment]
一看就是代码经验开发经验不足，别丢人现眼，人数一多这种根本不现实

**Comment by ygxiuming** [comment]
你是不是评论错地方了？有点尴尬，我以为你在说我哦，邮件看不到全的，不好意思



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月19日(周四) 晚上10:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XYZliang/JiangxiYouthStudyMaker] 多人学习版本、不用excel表格、直接用数据; (Issue #19)




 
你看你自己改的什么鬼
 newstr = text.split('吴') ，我也是看笑了
 数据全放代码里方便管理？

**Comment by XYZliang** [comment]
> 你是不是评论错地方了？有点尴尬，我以为你在说我哦，邮件看不到全的，不好意思
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月19日(周四) 晚上10:08 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [XYZliang/JiangxiYouthStudyMaker] 多人学习版本、不用excel表格、直接用数据; (Issue #19) 你看你自己改的什么鬼 newstr = text.split('吴') ，我也是看笑了 数据全放代码里方便管理？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

还真是，误伤友军，sorry
