### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by ALitKi** [XYZliang/JiangxiYouthStudyMaker#22]
求解

**Comment by XYZliang** [comment]
你手动学一个试试看，后台也没数据，别乱喊不行啊。。。。。

**Comment by Zzzz0077** [comment]
现在真的不行了！！，好像绑定了微信的openid，而且后台会验证这个openid，大佬有什么办法可以绕过这个验证嘛

**Comment by Zzzz0077** [comment]
![image](https://github.com/XYZliang/JiangxiYouthStudyMaker/assets/131767959/568cbd3f-ba3e-4f0a-9817-3eb21852cdc1)

**Comment by XYZliang** [comment]
> ![image](https://user-images.githubusercontent.com/131767959/250263578-568cbd3f-ba3e-4f0a-9817-3eb21852cdc1.png)

已了解，合并到 #23
