### ISSUE TITLE
大学习更新了一个月，好像不能用了，作者大大快来救救团支书们

### ISSUE THREAD

**Issue by Zzzz0077** [XYZliang/JiangxiYouthStudyMaker#23]
作者大大，我有一个团市委内部的群，里面会跟进青年大学习的最新通知，需要的话可以加我微信：********，我把最新的消息告诉你，现在通过抓包发现是大学习绑定微信openid了，可能以后都刷不了了

**Comment by XYZliang** [comment]
如果是真的需要openid了，那只能去获取大家的openid了，我记得之前的后台数据里包含了openid，等我明天看看后台数据里能不能再提取出来。
另外注意保护自己隐私哦

**Comment by XYZliang** [comment]
我就不用群了，后续有什么通知告诉我就好哈哈，我已经毕业了

**Comment by Zzzz0077** [comment]
http://106.225.141.143:8103/ 这个是最新的后台管理账号，如果需要账号密码的话我这边可以提供

**Comment by Zzzz0077** [comment]
如果不好批量获取openid的话，能不能试试别的方法 骗过这个验证，让后台能有记录

**Comment by ALitKi** [comment]
+1，我这里也可以提供，求大佬修复，团委要求要刷两期，可以实现嘛？

**Comment by XYZliang** [comment]
> +1，我这里也可以提供，求大佬修复，团委要求要刷两期，可以实现嘛？

现在确定是真用不了了是吧，我毕业了没法测试，近期可能有空我去看看能不能找别的办法

**Comment by Zzzz0077** [comment]
作者大大我这边可以给你提供帮助，我有后台账号可以测试数据，需要的话加我微信

**Comment by XYZliang** [comment]
> 作者大大我这边可以给你提供帮助，我有后台账号可以测试数据，需要的话加我微信

经过简单尝试，已经找到解决办法，但是目前硕士开学事务繁忙。最晚下周末实现。现在你要做的是，疯狂催一下班上同学，确保大家最近至少有学过一次，我才能获取到他们的id从而去学习，并且理论上后顾无忧。

**Comment by Zzzz0077** [comment]
> > 作者大大我这边可以给你提供帮助，我有后台账号可以测试数据，需要的话加我微信
> 
> 经过简单尝试，已经找到解决办法，但是目前硕士开学事务繁忙。最晚下周末实现。现在你要做的是，疯狂催一下班上同学，确保大家最近至少有学过一次，我才能获取到他们的id从而去学习，并且理论上后顾无忧。

好的，现在大学习还没有正式开始，大概率下个礼拜，期待作者大大的更新！！！

**Comment by XYZliang** [comment]
> > > 作者大大我这边可以给你提供帮助，我有后台账号可以测试数据，需要的话加我微信
> > 
> > 
> > 经过简单尝试，已经找到解决办法，但是目前硕士开学事务繁忙。最晚下周末实现。现在你要做的是，疯狂催一下班上同学，确保大家最近至少有学过一次，我才能获取到他们的id从而去学习，并且理论上后顾无忧。
> 
> 好的，现在大学习还没有正式开始，大概率下个礼拜，期待作者大大的更新！！！

新版本已经发布

**Comment by XYZliang** [comment]
> 作者大大，我有一个团市委内部的群，里面会跟进青年大学习的最新通知，需要的话可以加我微信：********，我把最新的消息告诉你，现在通过抓包发现是大学习绑定微信openid了，可能以后都刷不了了

这个群能拉人吗，如果可以的话我进去盯着看有没有新变动哈哈哈哈，可以拉人的话麻烦把你的微信通过我主页的邮箱发我
