### ISSUE TITLE
求作者大大更新个脚本

### ISSUE THREAD

**Issue by ALitKi** [XYZliang/JiangxiYouthStudyMaker#24]
新的学期开始了，苦逼团支书又要开始刷青年大学习了。求作者大大救救

**Comment by XYZliang** [comment]
经过简单尝试，已经找到解决办法，但是目前硕士开学事务繁忙。最晚下周末实现。现在你要做的是，疯狂催一下班上同学，确保大家最近至少有学过一次，我才能获取到他们的id从而去学习，并且理论上后顾无忧。

**Comment by ALitKi** [comment]
好的，谢谢大佬

**Comment by XYZliang** [comment]
已经完成
