### ISSUE TITLE
节前团省委那边增加了手机号码作为个人识别的唯一标识，这个会影响正常刷人数嘛

### ISSUE THREAD

**Issue by Zzzz0077** [XYZliang/JiangxiYouthStudyMaker#25]

**Comment by XYZliang** [comment]
所需要的数据在下个版本全部都会自动抓取，无需操心。代码已经完成90%，待新大学习开启后进一步测试即可

**Comment by Zzzz0077** [comment]
好的，我这边随时跟进大学习的最新进度，有新进展我会在issue上留言，辛苦作者大大了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月12日(星期四) 中午1:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XYZliang/JiangxiYouthStudyMaker] 节前团省委那边增加了手机号码作为个人识别的唯一标识，这个会影响正常刷人数嘛 (Issue #25)





 
所需要的数据在下个版本全部都会自动抓取，无需操心。代码已经完成90%，待新大学习开启后进一步测试即可

**Comment by Zzzz0077** [comment]
2023年第19期大学习今天更新了！！！，团省委那边新增了小程序版大学习，跟H5是一样的后台，会提示验证微信手机号

**Comment by XYZliang** [comment]
> 2023年第19期大学习今天更新了！！！，团省委那边新增了小程序版大学习，跟H5是一样的后台，会提示验证微信手机号

收到，最迟周五前测试好做好。第一次建议完完全全让同学自己去学习一次，保证后台的数据正确，这样被我程序抓取好后面才能高枕无忧

**Comment by Zzzz0077** [comment]
http://203.76.241.4:8103/ 原先大学习网站打不开的话可以试试这个

**Comment by XYZliang** [comment]
> http://203.76.241.4:8103/ 原先大学习网站打不开的话可以试试这个

这个好像也打不开？

**Comment by Zzzz0077** [comment]
电脑端登陆  http://mp.jxqingtuan.cn/  用这个 访问协议不一样
手机直接登陆  https://mp.jxqingtuan.cn/  如果遇上点登陆按键没有反应的情况
可以退出微信重新进行登陆

**Comment by XYZliang** [comment]
感谢，可以进去了
2023年10月26日 +0800 15:58 Zzzz0077 ***@***.***>，写道：

**Comment by XYZliang** [comment]
新版本已就绪
