### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by leiandpan** [XYZliang/JiangxiYouthStudyMaker#3]
程序成功运行，但是后台记录查不到，依旧显示未学习，目前不太清楚原因，再观察看看

**Comment by XYZliang** [comment]
上周四开始需要openid，但我在使用多人版发现openid可以跳过，后台也能有记录，还在研究如何跳过

**Comment by leiandpan** [comment]
不知道邮箱回复您能不能看见，我在抓包的时候发现，后台无记录的原因是：xlrd在读取整数的时候会把它变成小数，如111100变成111100.0，于是出现
后台无记录的情况，把表格修改成文本之后，后台就有记录了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 晚上8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XYZliang/JiangxiYouthStudyMaker] 问题 (Issue #3)





 
上周四开始需要openid，但我在使用多人版发现openid可以跳过，后台也能有记录，还在研究如何跳过

**Comment by XYZliang** [comment]
确实是如此！我说为什么多人提交版不提交openid都能正常学习。。。。。感谢，我修改一下脚本

> 不知道邮箱回复您能不能看见，我在抓包的时候发现，后台无记录的原因是：xlrd在读取整数的时候会把它变成小数，如111100变成111100.0，于是出现 后台无记录的情况，把表格修改成文本之后，后台就有记录了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月22日(星期二) 晚上8:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [XYZliang/JiangxiYouthStudyMaker] 问题 (Issue #3) 上周四开始需要openid，但我在使用多人版发现openid可以跳过，后台也能有记录，还在研究如何跳过 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by ALitKi** [comment]
为啥我的填了整数后台有记录(也变成了小数)，但使用文本之后后台就没有记录了
