### ISSUE TITLE
VSCODE错误提示FileNotFoundError: [Errno 2] No such file or directory: 'Data.xlsx'

### ISSUE THREAD

**Issue by ALitKi** [XYZliang/JiangxiYouthStudyMaker#5]
找不到Data.xlsx,是哪个地方配置错了吗？求大佬解答
![image](https://user-images.githubusercontent.com/39232323/163241244-2c46f6c5-676a-418b-9ae3-bfd71fd1de51.png)

**Comment by ALitKi** [comment]
Traceback (most recent call last):
  File "d:\04_file\Desktop\JiangxiYouthStudyMaker-main\duoren\makers.py", line 51, in <module>
    data = xlrd.open_workbook(r'Data.xlsx')
  File "C:\Users\24244\AppData\Local\Programs\Python\Python310\lib\site-packages\xlrd\__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Data.xlsx'

**Comment by ALitKi** [comment]
Data.xlsx文件已经配置好了，但是就是有这个错误提示？

**Comment by XYZliang** [comment]
额，我不熟悉vscode，但是可以试试这样：
data = xlrd.open_workbook(r'./Data.xlsx')
或者
data = xlrd.open_workbook(r'd:\04_file\Desktop\JiangxiYouthStudyMaker-main\duoren\Data.xlsx’)

**Comment by ALitKi** [comment]
已经解决了，谢谢大佬

**Comment by ALitKi** [comment]
大佬有捐赠渠道吗
