### ISSUE TITLE
大佬有时间做一个最新的后台的查询吗？小团支书非常渴望。

### ISSUE THREAD

**Issue by flyleixin** [XYZliang/JiangxiYouthStudyMaker#6]

**Comment by XYZliang** [comment]
可以的，后面有时间一定会开发，我也是需要查学院的完成率未完成率然后去催，但是得等这个学期期末过了

**Comment by ygxiuming** [comment]
你好，我也想写一个查询后台的，但是我碰到就算我自己登录系统有时候都登陆不进去，出现token出错，不晓得你有没有出现，这个怎么解决百思不得其解。

**Comment by XYZliang** [comment]
这个系统不大稳定，等我期末考试完来看看

**Comment by XYZliang** [comment]
新程序已经实现一键导出未完成的同学
