### ISSUE TITLE
浏览器已经打不开 江西共青团 青年大学习的链接了

### ISSUE THREAD

**Issue by cuncun-edg** [XYZliang/JiangxiYouthStudyMaker#7]
![image](https://user-images.githubusercontent.com/77426305/166234189-96598904-029b-4d3a-a24a-049869c54418.png)

**Comment by ygxiuming** [comment]
我写了个团委id查询的脚本，你可以看看：https://github.com/ygxiuming/QN-big-study

**Comment by XYZliang** [comment]
> 我写了个团委id查询的脚本，你可以看看：https://github.com/ygxiuming/QN-big-study

可以使用上面的脚本进行查询，我已经把所有id提取出来了，但是临近期末考试没空分析数据

**Comment by cuncun-edg** [comment]
好，我忘了我会抓包😂，已解决


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月21日(周六) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XYZliang/JiangxiYouthStudyMaker] 浏览器已经打不开 江西共青团 青年大学习的链接了 (Issue #7)




  
我写了个团委id查询的脚本，你可以看看：https://github.com/ygxiuming/QN-big-study
  
可以使用上面的脚本进行查询，我已经把所有id提取出来了，但是临近期末考试没空分析数据
 
&mdash;
