### ISSUE TITLE
2022年5月18日，又更新了，记录不到数据了

### ISSUE THREAD

**Issue by zZcoming** [XYZliang/JiangxiYouthStudyMaker#8]

**Comment by zZcoming** [comment]
研究了一下，失效是因为“http://osscache.vol.jxmfkj.com/html/assets/js/course_data.js”没有及时更新，courseId还是12，但是这周已经是13了，别的没问题。

**Comment by ALitKi** [comment]
> 研究了一下，失效是因为“[http://osscache.vol.jxmfkj.com/html/assets/js/course_data.js”没有及时更新，courseId还是12，但是这周已经是13了，别的没问题。](http://osscache.vol.jxmfkj.com/html/assets/js/course_data.js%E2%80%9D%E6%B2%A1%E6%9C%89%E5%8F%8A%E6%97%B6%E6%9B%B4%E6%96%B0%EF%BC%8CcourseId%E8%BF%98%E6%98%AF12%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E5%91%A8%E5%B7%B2%E7%BB%8F%E6%98%AF13%E4%BA%86%EF%BC%8C%E5%88%AB%E7%9A%84%E6%B2%A1%E9%97%AE%E9%A2%98%E3%80%82)
大佬这个有解决方法吗

**Comment by kongminhao** [comment]
简单，直接改成return 13 凑合一下。之后有问题再说。

**Comment by kongminhao** [comment]
重新分析了一下，似乎现在应该请求这个api来获取最新的数据了，我稍后提个 pr 。http://osscache.vol.jxmfkj.com/pub/vol/volClass/current

**Comment by XYZliang** [comment]
正解，已合并
